name: ci

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker registry
        uses: docker/login-action@v1 
        with:
          registry: registry.lennart-austenfeld.de
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.lennart-austenfeld.de/tentris:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
